[package]
name = "rust-tcp"
version = "0.1.0"
edition = "2024"

[lib]
name = "rust_tcp"
path = "src/lib.rs"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs"

[[bin]]
name = "audiotest"
path = "src/bin/audiotest.rs"

[dependencies]
anyhow = "1.0.103"
tokio = { version = "1.52.3", features = ["full"] }
base64 = "0.22"
yt-dlp = "2.8.3"
rodio = { version = "0.22.1" }
aes-gcm = "0.11.0"
serde_json = "1.0.151"
